### ISSUE TITLE
Run A Tracker

### ISSUE THREAD

**Issue by f1carreras** [meehow/privtracker#11]
Is it possible to run a 'private' tracker using a custom announce url?

I don't want to use any of the existing torrent platform like Unit3d, Gazelle, etc...
Just wondering if possible to setup a website of my own adding torrents using **privtracker** announce URL using my own domain.

Is it possible?

**Comment by Epy** [comment]
Yes it is :)
I run it with a systemd unit config file and that's it.
No database required. 
It's Go, if the system you want as a server has Go language abilities, it will run :)
