### ISSUE TITLE
Use longer 32-character passkey format that real private trackers use?

### ISSUE THREAD

**Issue by Pentaphon** [meehow/privtracker#2]
I realize 16 characters in the URL is probably ok for now, but why not just use the longer 32-character passkey format that real private trackers use to "futureproof" the service?

**Comment by ulnasensei** [comment]
The room IDs are just randomly generated alphanumeric strings. AFAIK there is no character limit for the announce URL, it's just the generator is using 16 char length. You can use whatever you want as the room ID and it will just work they are not stored anywhere, and there is no server-side room ID validation. The server just connects peers that use the same room ID.

https://github.com/meehow/privtracker/blob/master/docs/index.html

```
function makeRoom(length) {
			var roomID = '';
			var characters = 'abcdefghijklmnopqrstuvwxyz0123456789';
			var charactersLength = characters.length;
			for (var i = 0; i < length; i++) {
				roomID += characters.charAt(Math.floor(Math.random() * charactersLength));
			}
			var urls = document.getElementsByClassName('url');
			for (var i = 0; i < urls.length; i++) {
				urls[i].innerText = urls[i].innerText.replace('{{room}}', roomID);
			}

			document.getElementById('hidden').style.display = 'block';
		}
```

**Comment by Pentaphon** [comment]
> You can use whatever you want as the room ID and it will just work they are not stored anywhere, and there is no server-side room ID validation. The server just connects peers that use the same room ID.

Then there should be some kind of notice or function on the website that lets people know that so they can enhance their privacy by using their own random number generator to create any size room ID they want. Right now it's a little too basic.

**Comment by meehow** [comment]
16 characters from 36 character set, that's 7958661109946400884391936 combinations. If someone will manage to make 1000 requests to the server per seconds it will take 7958661109946400884391936/1000/3600/24/365 = 252367488265677 years to brute force it.

**Comment by Pentaphon** [comment]
> 16 characters from 36 character set, that's 7958661109946400884391936 combinations. If someone will manage to make 1000 requests to the server per seconds it will take 7958661109946400884391936/1000/3600/24/365 = 252367488265677 years to brute force it. And you need to repeat it for every file (info hash) you are looking for.

I still think real private trackers use 32 character passwords for a reason and following suit seems reasonable. There's no reason not to.

**Comment by meehow** [comment]
> There's no reason not to.

Agreed. Feel free to open a pull request.

**Comment by SinTan1729** [comment]
It's been about a month without anyone else opening a PR, so I decided to do it.

**Comment by meehow** [comment]
thanks, merged
