### ISSUE TITLE
Domain is hard-coded

### ISSUE THREAD

**Issue by dgw** [meehow/privtracker#5]
Such a simple application seems to just cry out for self-hosting, e.g. by users who plan to use it a lot and don't want to strain the public instance, or users who have privacy/control concerns about the public server.

I'm a noob Go developer, but if I were to modify this such that it accepted simple configuration of the domain name at runtime (via an environment variable or a config file in the same directory as the binary), would you accept a pull request for that feature? It seems like an easy way for me to get my feet wet in Go without writing something from scratch, and (hopefully) provide a useful contribution to an existing project along the way. 🙂

**Comment by meehow** [comment]
Sure, all reasonable contributions are welcomed, but it seems like main place where we need to configure a domain name is just static index.html file.

**Comment by dgw** [comment]
_My_ main motivation for suggesting this was seeing the [HTTP-to-HTTPS redirect](https://github.com/meehow/privtracker/blob/822973b970f15e9a3190596d707c49bfd945ae8a/main.go#L100) and [enforced root domain](https://github.com/meehow/privtracker/blob/822973b970f15e9a3190596d707c49bfd945ae8a/main.go#L117-L119) for the index page.

I hadn't looked yet, and thought the index page of the live site got compiled somehow. Turns out the whole `docs/` folder just gets deployed as-is. AFAICT the Jekyll `_config.yml` isn't even used.

Will need to think about how to approach this, as it's not a pure-Go problem after all. For the Go side, something lightweight like https://github.com/ufoscout/go-up seems a natural choice, but now I have to figure out how to take the same configuration and apply it to both the HTML and Go code.

**Comment by dgw** [comment]
@ulnasensei deserves another shout-out for coming up with—in hindsight—a dead simple solution for the "how to change the HTML?" roadblock I hit when I looked at implementing this myself: just use JavaScript.

Sometimes you just need someone else to come along and show you how dense you are 😉 … or at least, I do!
