### ISSUE TITLE
build on debian 11

### ISSUE THREAD

**Issue by gzpapp** [meehow/privtracker#6]
lo lo,

I'm trying to build on debian 11

$ make
go build
go: downloading github.com/gofiber/fiber/v2 v2.40.1
go: downloading golang.org/x/crypto v0.4.0
go: downloading github.com/jackpal/bencode-go v1.0.0
go: downloading golang.org/x/sys v0.3.0
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/valyala/fasthttp v1.43.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/rivo/uniseg v0.4.3
go: downloading golang.org/x/net v0.4.0
go: downloading github.com/valyala/tcplisten v1.0.0
go: downloading github.com/klauspost/compress v1.15.13
go: downloading github.com/andybalholm/brotli v1.0.4
go: downloading golang.org/x/text v0.5.0
../../go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /home/gzp/go/pkg/mod/github.com/rivo/uniseg@v0.4.3
make: *** [Makefile:3: build] Error 1

**Comment by meehow** [comment]
Debian 11 comes with Golang 1.15, but the oldest version I managed to compile current code with was 1.17.
go.mod needs to be updated, but it doesn't solve your issue anyway. Or you download newer go, or we create some basic Dockerfile (or Nix). Something like:
```
FROM golang
WORKDIR /src
COPY . ./
RUN make
```

**Comment by gzpapp** [comment]
Successfully built with go version go1.20.4 linux/amd64 on Debian 11.7

**Comment by meehow** [comment]
Than you. Supporting go version included to every distro would be a bit problematic.
