### ISSUE TITLE
IPv6 support in privtracker v1.0.2

### ISSUE THREAD

**Issue by iamalexei** [meehow/privtracker#7]
After updating to v1.0.2 I'm not able to connect to the locally installed privtracker via IPv6. The previous version of privtracker works fine.

OS: Windows 10 x64 Home, 22H2;
privtracker v1.0.2 is allowed to receive incoming connections in Windows Firewall.

**Comment by meehow** [comment]
That's due to changed framework and it's default configuration. Could you test [v1.0.3](https://github.com/meehow/privtracker/releases/tag/v1.0.3) ? Unfortunately prefork mechanism will be disabled, but now it should work with both: IPv4 and IPv6.

**Comment by iamalexei** [comment]
@meehow Thank you! Yes, both IPv4 and IPv6 protocols work in [v1.0.3](https://github.com/meehow/privtracker/releases/tag/v1.0.3)
